# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Sources for pods
    source 'https://github.com/CocoaPods/Specs.git'

target 'bike_marketplace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bike_marketplace
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'Firebase/Analytics'
    pod 'Firebase/Storage'
    pod 'PhoneNumberKit', '~> 3.1'
end
